### PR TITLE
Update project_building_blocks.md

### PR DESCRIPTION
**Pull request by malaikaMI**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @malaikaMI, can you explain you reasoning on this change please? 🙂 

It doesn't seem like something that needs to change imo.

**Comment by malaikaMI** [comment]
https://www.theodinproject.com/lessons/building-blocks Project 1: Caesar Cipher  on the 8th line "There’s a brief video about it from Harvard’s CS50 class" ,I deleted the word "brief" because it is a unnecessary word 
 and also it is not a brief video.

**Comment by KevinMulhern** [comment]
Fair enough, under three minutes is pretty brief though 😛

Thanks for the PR @malaikaMI

**Comment by malaikaMI** [comment]
Thanks!

**Comment by malaikaMI** [comment]
Thanks!

**Pull request merged**
