### PR TITLE
Update 'project_advanced_building_blocks.md' with link to Enumerable …

### PR DESCRIPTION
**Pull request by turbopro**
…Methods solution

### CODE REVIEW

**Comment by turbopro** [comment]
Ran into some errors on a failed merge with the upstream master.  So, I'm closing this request until I resolve the conflicts.

Thanks

**Comment by turbopro** [comment]
Reopened after resolving merge conflicts with upstream master.

Hopefully, all is ok now.

**Comment by JonathanYiv** [comment]
Closing due to 1 week of inactivity

**Comment by turbopro** [comment]
Gents hi,

Sorry, I was sick the last week and out of touch.

I removed the offending files.


cheers

**Pull request merged**
