### PR TITLE
Fixed another broken link due to redesign.

### PR DESCRIPTION
**Pull request by JonathanYiv**
Is there a way to write a route that would fix all these? I'm sure a lot of external links might be broken too.

### CODE REVIEW

**Comment by JonathanYiv** [comment]
In reference to https://github.com/TheOdinProject/theodinproject/issues/824

**Comment by KevinMulhern** [comment]
Thanks @JonathanYiv 👍

**Comment by mindovermiles262** [comment]
Shouldn't we be able to fix these via a find and replace all?

**Comment by KevinMulhern** [comment]
Thats a good idea @mindovermiles262 😄

**Pull request merged**
