### PR TITLE
Move Ruby Lessons Over

### PR DESCRIPTION
**Pull request by KevinMulhern**
This moves all the Ruby lessons from the web development 101 and the ruby programming courses in the curriculum repo over here.

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Merging won't break TOP, right?

**Comment by KevinMulhern** [comment]
It's possible @mindovermiles262, it would certainly cut down on the amount of work we have to do when adding new lessons.

It would be pretty awesome to dynamically create the seeds file with the files in a repo. We are going to have to change the way the seeds file works to incorporate tracks so it might make sense to do it along with that project 😄

**Comment by mindovermiles262** [comment]
@KevinMulhern 

if we standardize the naming convention it will be simple to write a script to pull all `project_ ... .md` files.  We could also incorporate some kind of yaml header similar to what Jekyll does to add more information/metadata to each lesson.

**Comment by KevinMulhern** [comment]
We have a couple of gotchas to consider, the positions of a lesson/project in a course are created in the seeds file. I suppose we could add that to the file name of a though. 

I'm not familiar with the way jekyll adds meta data, but do you have an example?

**Comment by mindovermiles262** [comment]
Using Jekyll you add a header,
```
---
type post
date 2017-09-09
title Example Title
---
```
and then you can use it later (or perhaps in a seed file?)
```
<h1>{ page.title }</h1>
```

I haven't looked into this at all but it might be something we could add.

**Comment by leosoaivan** [comment]
> It would be pretty awesome to dynamically create the seeds file with the files in a repo. 

I thought that's how we pulled in the curriculum into the main site?

**Comment by KevinMulhern** [comment]
@leosoaivan nah we have to manually add each lesson, one of the attributes we give a lesson is a `url` which is the url to the lesson md file on github. That allows it to pull in the lesson content.

A set up like @mindovermiles262 is describing cuts out all of that, but might make it harder to debug problems if there are any with the seeds file. I think we should definitely experiment with this though. Adding lessons in manually is error prone so the trade off in debugging would be worth it.

**Pull request merged**
